name: comau_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core Robotics and Scientific Stack
  - numpy=1.26.4
  - roboticstoolbox-python
  - spatialmath-python
  - scipy
  - matplotlib
  # Web Application Backend
  - flask
  # Notebook Interactivity
  - ipywidgets
  - notebook